server:
  port: 9099

spring:
  application:
    name: www-server
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  datasource:
    name: yaw
    url: jdbc:mysql://localhost:3306/www_base
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wg.www.domain